// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/comrade-landing/ComradeLanding.tsx": () => import("../components/mockups/comrade-landing/ComradeLanding.tsx"),
  "./components/mockups/comrade-landing/ComradeLandingOrbit.tsx": () => import("../components/mockups/comrade-landing/ComradeLandingOrbit.tsx")
};
